### ISSUE TITLE
Cannot find signingKey/ANDROID_SIGNING_KEY

### ISSUE THREAD

**Issue by PainterHalver** [ilharp/sign-android-release#12]
I've set the secrets and checked that decoded base64 keystore is exactly the same as the original, but still cannot find signing key.

yml:
```
name: "Release Build"

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17.x'
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build apk
        run: ./gradlew assembleRelease
      - uses: ilharp/sign-android-release@v1
        name: Sign app APK
        id: sign_app
        with:
          releaseDir: app/build/outputs/apk/release
          signingKey: ${{ secrets.ANDROID_SIGNING_KEY }}
          keyAlias: ${{ secrets.ANDROID_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
          buildToolsVersion: 33.0.0
      - name: Rename to app-release.apk
        run: mv ${{steps.sign_app.outputs.signedFile}} app-release.apk
      - name: Publish release APK
        uses: actions/upload-artifact@v3
        with:
          name: Signed app bundle
          path: app-release.apk
```

![image](https://user-images.githubusercontent.com/73751932/198812642-5109d6a6-89f5-4db0-a76d-c03bbca5d748.png)

All secrets set:
![image](https://user-images.githubusercontent.com/73751932/198812497-c36f1363-ba63-42e2-b5ad-f0cda793e727.png)
