### ISSUE TITLE
steps.sign_app.outputs.signedFile is not returning the correct path

### ISSUE THREAD

**Issue by DominusExult** [ilharp/sign-android-release#18]
I've run into trouble with this.

Using this action in https://github.com/exult/exult/blob/master/.github/workflows/snapshots-android.yml#L80 and then renaming & copying  the apk to another folder:
```
 - name: Sign APK
        if: ${{ env.EXULT_REPO_ALIVE == 'true' }}
        uses: ilharp/sign-android-release@v1
        id: sign_app
        with:
          releaseDir: /home/runner/work/exult/build/android/app/build/outputs/apk/release
          signingKey: ${{ secrets.ANDROID_SIGNING_KEY }}
          keyAlias: ${{ secrets.ANDROID_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
      - name: Save release artifact
        if: ${{ env.EXULT_REPO_ALIVE == 'true' }}
        run: cp ${{steps.sign_app.outputs.signedFile}} ./android-snapshot/exult-snapshot-signed.apk
```
The output of the signing action:
```
 Signing APK file.
  /usr/local/lib/android/sdk/build-tools/33.0.0/apksigner sign --ks *** --ks-key-alias *** --ks-pass pass:*** --out /home/runner/work/exult/build/android/app/build/outputs/apk/release/app-release-unsigned-aligned-signed.apk --key-pass pass:*** /home/runner/work/exult/build/android/app/build/outputs/apk/release/app-release-unsigned-aligned-temp.apk
Successfully signed 1 file(s).
```

But the "Save release artifact" action has this:

```
env:
    ...
    ANDROID_SIGNED_FILE: /home/runner/work/exult/exult/home/runner/work/exult/build/android/app/build/outputs/apk/release/app-release-unsigned-aligned-signed.apk
    ANDROID_SIGNED_FILES: /home/runner/work/exult/exult/home/runner/work/exult/build/android/app/build/outputs/apk/release/app-release-unsigned-aligned-signed.apk
    ANDROID_SIGNED_FILES_COUNT: 1
cp: cannot stat '/home/runner/work/exult/exult/home/runner/work/exult/build/android/app/build/outputs/apk/release/app-release-unsigned-aligned-signed.apk': No such file or directory
```
Why does it add `/home/runner/work/exult/exult` in front of the path?
