### ISSUE TITLE
Not signing AAB

### ISSUE THREAD

**Issue by DatL4g** [ilharp/sign-android-release#2]
I build an apk file and an aab file and move them to the same location.

```bash
$ ls ./app/release/
app-release-unsigned.apk
app-release.aab
```

Then I want to sign them both with this action
```yml
- uses: ilharp/sign-android-release@v1
      id: sign_app
      with:
        releaseDir: app/release
        signingKey: ${{ secrets.ANDROID_SIGNING_KEY }}
        keyAlias: ${{ secrets.ANDROID_KEY_ALIAS }}
        keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
        buildToolsVersion: 30.0.2
```

However the action signs the apk file only
```bash
Now sign 1 files:
- app-release-unsigned.apk
...
Verification succesful
  Signing APK file.
  /usr/local/lib/android/sdk/build-tools/30.0.2/apksigner sign --ks *** --ks-key-alias *** --ks-pass pass:*** --out app/release/app-release-unsigned-signed.apk app/release/app-release-unsigned-temp.apk
Successfully signed 1 files.
```

The aab file is ignored
